name: CD
on:
  workflow_run:
    workflows: [CI]
    branches: [main]
    types: [completed]
jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ci.yml
          workflow_conclusion: success
          name: build

      - name: Add SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts
          
      - name: Deploy
        run: |
          ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} "rm -rf /home/${{ secrets.USERNAME }}/build/*"
          scp -r ./* ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/home/${{ secrets.USERNAME }}/build/
          ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} "chmod -R 755 /home/${{ secrets.USERNAME }}/build"
          ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} "sudo systemctl restart nginx"