name: CD
on:
  workflow_run:
    workflows: [CI]
    branches: [main]
    types: [completed]
jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: build
      - name: Deploy
        run: |
          ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} "rm -rf /home/${{ secrets.USERNAME }}/build/*"
          scp -r ./* ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/home/${{ secrets.USERNAME }}/build/
          ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} "chmod -R 755 /home/${{ secrets.USERNAME }}/build"
          ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} "sudo systemctl restart nginx"