name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: Install Dependencies and Build
        run: |
          # 최상위 의존성 설치
          npm install
          
          # Server 빌드 (TypeScript -> JavaScript)
          cd Server 
          echo "${{ secrets.SERVER_ENV }}" > .env
          npm install
          npm run build
          cd ..
          
          # Client 빌드
          cd Client
          npm install
          CI=false npm run build
          cd ..

      - name: Upload Server Build
        uses: actions/upload-artifact@v4
        with:
          name: server-build
          path: Server/dist/
          retention-days: 1
          
      - name: Upload Client Build
        uses: actions/upload-artifact@v4
        with:
          name: client-build
          path: Client/build/
          retention-days: 1